name: CodeClimate Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codeclimate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Ruby (si usas Ruby, por ejemplo)
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install dependencies
        run: |
          bundle install

      - name: Run tests (si usas Ruby)
        run: |
          bundle exec rspec # O el comando correspondiente para tu proyecto

      - name: Set up CodeClimate
        uses: codeclimate/test-reporter-action@v2
        with:
          repo-token: ${{ secrets.CODECLIMATE_REPO_TOKEN }}

      - name: Run CodeClimate analysis
        run: |
          # Esto ejecuta el análisis de CodeClimate
          bundle exec codeclimate analyze
